### ISSUE TITLE
Inability to login after following welcome link

### ISSUE THREAD

**Issue by matelau** [erlef/website#107]
Hello,  I recently signed up to be a member of ERLEF and after sign-up received a link. Upon clicking this link I was returned back to the sign-up page. ie: 
![image (2)](https://user-images.githubusercontent.com/1214752/72476510-a165e900-37aa-11ea-9e55-47312b070767.png)

Upon navigating the site I did not find a component that would allow me to log in. I believe the expected behavior is that I am able to view my profile like the example below. 

![image (1)](https://user-images.githubusercontent.com/1214752/72476582-cc503d00-37aa-11ea-8e5b-2fc77e29e60d.png)

Either way, I think it would be beneficial to have a separate login component that would allow me to view my profile, and do the other things members are allowed to do 😄 with or without the initial link.

**Comment by starbelly** [comment]
hi @matelau I agree. This is in flux at the moment and will be made available as soon as possible.  For the moment you can view your member profile by visiting https://erlangecosystemfoundation.wildapricot.org/Sys/Profile 

Thank you for raising this and your patience.

**Comment by nurugger07** [comment]
@starbelly I noticed this today too :)

**Comment by starbelly** [comment]
Closing this as this is resolved in master and will be going out 🔜
