### ISSUE TITLE
Academic Papers - Differentiate between direct and paywalled links

### ISSUE THREAD

**Issue by pdgonzalez872** [erlef/website#108]
As title suggests, we should be able to differentiate between the links on the page.

**Comment by nurugger07** [comment]
@pdgonzalez872 definitely a good idea 👍 We will get something added

**Comment by pdgonzalez872** [comment]
@nurugger07 great! Maybe just keeping in mind when something gets added should be enough. We don't have papers coming in like hot cakes (unfortunately) :)

So if paywalled, we should just add to the title: `Something ... | Paywall`

**Comment by starbelly** [comment]
@nurugger07 resolved this issue when implementing the updated academic papers endpoint. 👍
