### ISSUE TITLE
add FOSDEM to the agenda

### ISSUE THREAD

**Issue by benoitc** [erlef/website#110]
can you add the Erlang, Elixir & Friends Devroom at fosdem 2020 to the Agenda ?

It will happen on Saturday, 1 February 2020. The link to the schedule is there: https://beam-fosdem.org/schedule/ . Thanks!

**Comment by pdgonzalez872** [comment]
@benoitc I was thinking about this: Should we create a public Google Calendar where we have a few owners and just display it on the webpage? Folks can then add/follow/export the events correctly, less friction to add stuff like location, can overlay your calendars to it. I remember there was a Formula 1 calendar and that was awesome (was discontinued though, unsure why).

I think we should probably be the source of truth for events/meetups in the community. Just another excuse for folks to come visit the website. But, with the current workflow, I don't think we can scale.

What are your thoughts?

**Comment by benoitc** [comment]
i would prefer to find a solution that doesn’t involve a google tool personnaly. Maybe we should list some alternatives for it?

But agree we should have something we can export and that handle timezones. not sure what we are using right now cc @starbelly

**Comment by pdgonzalez872** [comment]
We currently create the events by hand, In a Google friendly format:
https://github.com/erlef/website/tree/master/priv/events

Looks like there is a task to create the events so there is less manual thinkering:
https://github.com/erlef/website/blob/master/lib/mix/tasks/eef/gen/event.ex

**Comment by starbelly** [comment]
That is correct, it is still extremely clunky though and tedious, and at the end of the day this was a temporary solution.  I suppose one thing that would make it easier would be to make augment the mix task with prompts, perhaps it reaches out to various APIs to get adequate data and timestamps. This could also be done via the UI. However, I've been hesitant to do any further work while infrastructure comes together. 

 So, let's go over options: 

 - At one point it seemed we could leverage google calendar pull in events displayed on the site, but this proved to be folly unless you have a business account (or whatever terminology google uses). Regardless of whether we could get such an account or not, I think we should be moving away from google tools. We are global and as such some of our members and volunteers reside in countries in which google is not friendly to. In addition, we also have members and volunteers that very cognizant of their privacy and have great integrity in their politics. It's not right to tell these people : Too bad, so sad. Therefor, google is just off the table as far as I am concerned. 
 
 - Wildapricot does offer an events widget which seems to be suitable and makes sense to use provided they are essentially our database, so I'm leaning towards that, but can not test it out until next week per authorization processes within erlef that have not been completed yet.  

- There are other proprietary solutions that I looked at which looked promising, I'd have to go back through history to find those. 

- Another option is simply to have shared calendar provided via a caldav. This too is predicated on some things falling out of infrastructure. It may be a solid option though. 

 The above aside, I think we should think about how this should work in practice. My thinking is this:

 - Any member should be able to easily submit an event
 - There should be designated admin(s) for approving the event. 
 - Upon approval the event shows up on the site. 

With a custom database behind the app, this is pretty simple, it remains to be seen how simple this would be with third-party integrations and no database. However, do we agree that should be the flow in general?

**Comment by benoitc** [comment]
it should probably a new issue, can you add the fosdem to the agenda using current method ;)

**Comment by starbelly** [comment]
ahh yeah...

**Comment by pdgonzalez872** [comment]
@benoitc, fair, created a new issue: https://github.com/erlef/website/issues/114
