### ISSUE TITLE
Maybe replace current Events and Calendar mechanism?

### ISSUE THREAD

**Issue by pdgonzalez872** [erlef/website#114]
Following up on the discussion that started here: https://github.com/erlef/website/issues/110.

**Comment by nurugger07** [comment]
@pdgonzalez872 this is definitely being addressed as part of an overall site redesign. We want to have a better experience for visitors. We would like to have more of a filterable list format highlighting open CFPs, ticket sales, etc.

**Comment by pdgonzalez872** [comment]
@nurugger07 Awesome!

**Comment by starbelly** [comment]
This is done in master, so am closing this.

**Comment by pdgonzalez872** [comment]
Yay!
