### ISSUE TITLE
Add Academic Paper: Erlang as an alternative to a non-functional language for communication in a fault-tolerant IoT sensor network

### ISSUE THREAD

**Issue by pdgonzalez872** [erlef/website#134]
Title:
Erlang as an alternative to a non-functional language for communication in a fault-tolerant IoT sensor network

Details:
By Jimmy Holdö, Department of Computer Science and Engineering, UNIVERSITY OF GOTHENBURG, Gothenburg, Sweden 2019

Link: https://gupea.ub.gu.se/bitstream/2077/63387/1/gupea_2077_63387_1.pdf

I haven't been able to find Jimmy Holdö on Github to ask if we could link this paper (a master's thesis). I'm not sure they would care, but I don't want to assume incorrectly. Thoughts?

**Comment by starbelly** [comment]
Closed via #220
