### ISSUE TITLE
new logo for Enki Multimedia

### ISSUE THREAD

**Issue by benoitc** [erlef/website#173]
The logoEnki Multimedia has been refreshed, can you please change it ASAP on the website. 

I attached a version of it as PDF and PNG but let me know which width / height and format you need. 

Let me know.

[logo_v3_r.pdf](https://github.com/erlef/website/files/4292073/logo_v3_r.pdf)
![logo_v3_r](https://user-images.githubusercontent.com/14498/75967468-27113580-5ecc-11ea-9bc0-5cfc27a00fa1.png)

**Comment by starbelly** [comment]
The png will definitely do.

**Comment by starbelly** [comment]
@benoitc this has been deployed.

**Comment by benoitc** [comment]
thanks!
