### ISSUE TITLE
Alternative to google recaptcha

### ISSUE THREAD

**Issue by starbelly** [erlef/website#176]
We need an alternative to google recaptcha for the sake of our user's privacy and not to mention some of users would be shut out by even using google recaptcha per the country they are in. 

We only use this on the slack invite endpoint right now. Simple recaptcha's can be circumvented by bots quite easy unfortunately, but we want to restrict the slack invite form submission to humans.  

Suggestions are welcome.

**Comment by codeadict** [comment]
There are not many alternatives but probably worth to read https://kevv.net/you-probably-dont-need-recaptcha/, maybe a math question could be a good solution or even other kind of funny challenge

**Comment by starbelly** [comment]
@codeadict this is true, might not be worth it. I was thinking about bandwidth costs. That is the more bots hitting that end point and submitting bogus addresses (or valid addresses for bad actors) it will run up the bill.  

 But I could very much be over thinking that. The endpoint is rate limited after all.

**Comment by starbelly** [comment]
@codeadict you're right... and my logic on saving bandwidth is folly, going to remove the recaptcha 😁

**Comment by codeadict** [comment]
Yeah Rate limits will prevent lots of bot request, worst case you can identify bots and ban them with firewall rules or something else
