### ISSUE TITLE
Update packages to combat new lodash SEVERE vulnerability

### ISSUE THREAD

**Issue by gamebox** [erlef/website#18]
This was just published on 7/15/19.  https://www.npmjs.com/advisories/1065

This dep is used over 560 times in our dependency tree

**Comment by starbelly** [comment]
Will gladly take a PR. One thing to keep in mind is this app currently nodejs is limited to our asset pipeline. That said, I'm all for getting rid of insecure packages either via upgrade or removal when possible. 

👍 ❤️

**Comment by starbelly** [comment]
Oh, npmjs... yeah I looked at this again and while it seems mostly limited to runtime, it's still nasty.
