### ISSUE TITLE
Bug: submitting a stipend proposal on erlef.org leads to an Internal Server Error

### ISSUE THREAD

**Issue by josevalim** [erlef/website#186]
I have fully filled the form here: https://erlef.org/stipends/

Note there is a bug in the country selector widget as well:

<img width="279" alt="image" src="https://user-images.githubusercontent.com/9582/77049531-8ab95980-69c8-11ea-8a2c-358eda615f33.png">

It doesn't filter when I type a country name.

**Comment by josevalim** [comment]
Btw, the new website looks *amazing*.

**Comment by starbelly** [comment]
This seemed to be breakage from the design update. Have a PR open to fix this up. Another PR will be needed to resolve the actual issue if we value that widget.

**Comment by starbelly** [comment]
@josevalim The temporary fix for this has been deployed and so you should be able to submit your request now. Leaving this issue open until we decide that the bootstrap-select widget isn't worth having or we get to the bottom of the issue. At a a cursory glance it seemed all css related.

**Comment by starbelly** [comment]
@josevalim There was a second issue on the backend which is also just been fixed. If you tried to submit between now and 26 minutes ago it would have failed.

**Comment by starbelly** [comment]
Closing this issue as fixed/resolved.
