### ISSUE TITLE
Bug: we are listing "John Doe" as the contact person for media inquiries

### ISSUE THREAD

**Issue by josevalim** [erlef/website#187]
The bug can be found on this page: https://erlef.org/news/ - just search for John Doe. :)

**Comment by starbelly** [comment]
heh! So, I'm not sure who the contact here should be. @nurugger07 is chair of marketing so I would think this would go to him, and thus defer to him. This section is also worded such that it needs multiple contacts, I would a mailto link for simply marketing@.

**Comment by starbelly** [comment]
Opened up another quick fixup PR for this. Would rather just having marketing wg as the sole link vs poor Mr. John Doe.

**Comment by josevalim** [comment]
Yeah, i think linking to marketing is totally fine.

**Comment by starbelly** [comment]
The update for this has been deployed but am leaving the issue open for others to weigh in on.

**Comment by starbelly** [comment]
Closing this issue as stale.
