### ISSUE TITLE
Upgrade to phoenix 1.5

### ISSUE THREAD

**Issue by starbelly** [erlef/website#198]
See Chris McCord's handy dandy note book for upgrade detail : https://gist.github.com/chrismccord/e53e79ef8b34adf5d8122a47db44d22f

**Comment by RudolfMan** [comment]
I guess this issue was addressed in https://github.com/erlef/website/pull/205 and now can be closed.

**Comment by starbelly** [comment]
Ahh yes, thank you 👍
