### ISSUE TITLE
Discussion : How can we make contributing more ammenable? 

### ISSUE THREAD

**Issue by starbelly** [erlef/website#208]
There is a need to get members of the foundation more involved in the development of the site and for multiple reasons. First, we must understand what are the road blocks people face, second what can we do to either remove the road blocks completely or make the navigation into contributing a smoother and easier process. 

This requires reaching out to all working groups to suss out why they have not contributed or why they started to but stopped.  

There are a lot of little things we can surely do to make this process easier, at the very least people should be aware that opening up an issue (or a PR) is welcomed and the right protocol. After all, simply opening an issue and having dialog within that is in fact contribution. 

I would suggest that the scope of this discussion does not expand to the idea of a CMS. This may indeed be a long term solution that is warranted, but is certainly not a short term solution and doesn't solve any existing problems and roadblocks in the short term. So, let's avoid that discussion within this issue 😄

**Comment by tsloughter** [comment]
What does contribution mean? What would you expect to see working groups contribute to the site?

**Comment by starbelly** [comment]
Closing this as stale.

**Comment by paulo-ferraz-oliveira** [comment]
Bryan, I've seen bots do the same you're doing here. Do we want to continue doing it by hand, or potentially explore that? (I'm not sure if they're externally triggered, but would assume some type of TTL after which issues are closed).

**Comment by starbelly** [comment]
@paulo-ferraz-oliveira I'm not opposed to that.
