### ISSUE TITLE
Easy to find list of BEAM languages

### ISSUE THREAD

**Issue by adolfont** [erlef/website#214]
I was presenting the EEF site to a Portuguese speaking audience (Recursos relacionados à linguagem de programação Elixir https://youtu.be/SeOEdGtAwv0) and I missed a link to a list of BEAM languages.

Maybe put a link to this page https://github.com/llaisdy/beam_languages here "Our members include industry leaders who are dedicated to furthering state of the art for Erlang, Elixir, LFE and other technologies based on the BEAM."

**Comment by starbelly** [comment]
This sounds like it should be on the proposed community page perhaps?
