### ISSUE TITLE
Logos not showing up correctly on the Events page

### ISSUE THREAD

**Issue by ahw59** [erlef/website#217]
The posted corporate / event logos are not showing up properly on the LHS of the text
see page: https://erlef.org/events/

**Comment by starbelly** [comment]
Yeah, I talked to folks about this in regards to codebeam. They sent me logos, they need to be sized appropriately and then put into the system. Have not got a chance to do that yet.

**Comment by starbelly** [comment]
@ahw59 this has been resolved. Uploads objects to vultr by default is not allowing public access. Manually fixed up, need to see what we need to do in code (ExAWS.S3) to enable public access by default, as such I'm leaving this issue open.
