### ISSUE TITLE
Maybe add academic paper? 

### ISSUE THREAD

**Issue by pdgonzalez872** [erlef/website#219]
I saw that an academic paper containing Elixir and Phoenix was just released:
https://www.info.ucl.ac.be/~pvr/Neirinckx_47311500_Bastin_81031400_2020.pdf

I did 5 mins of research and think https://github.com/guiste10 and https://github.com/julien1bastin are the authors so I'm pinging them directly here, asking for their permission to add the paper to our existing papers. I also found

If the authors somehow get back to us (github, twitter, email) can we please add the paper to our list? I'm using this issue as a way to be transparent and have a source of truth. When/if I receive confirmation I'll update this issue with what I learned. Feel free to close it if you need to.

Thanks!

**Comment by pdgonzalez872** [comment]
After watching a video about the paper (ha!) here: https://www.youtube.com/watch?v=0Fhjua-0Tck&feature=emb_title, I believe  @bastinjul and @guiste10 are the authors. Hopefully valid Github handles. :)

**Comment by bastinjul** [comment]
Indeed we are the authors of this master thesis and we are delighted by your interest in it. You can add it to your list.
