### ISSUE TITLE
improve membership page

### ISSUE THREAD

**Issue by benoitc** [erlef/website#221]
The discussion today at Codebeam V makes me think we should improve this pag to clarify what is a member and what provides membership. Also like the sponsor page before pointing to wildapricot we should present the different tiers and their pricing.

**Comment by paulo-ferraz-oliveira** [comment]
Is this not done already? From @benoitc's description it seems https://members.erlef.org/join-us fits the bill, but I guess you might be mentioning the lack of a page before Wildapricot's. I think I've discussed this with Bryan a while back, so share your thoughts.

**Comment by starbelly** [comment]
This was resolved.  Wildapricot doesn't provide much in the way of making this page nice and I'm sure there's much room for improvement. If we want to improve this further, then another issue should be opened.
