### ISSUE TITLE
posting an event shouldn't require membership? 

### ISSUE THREAD

**Issue by benoitc** [erlef/website#222]
I tried to create an event by going on the link "Click here to submit an event" in the events page (https://erlef.org/events) but I get this error "The resource you requested requires that you are logged in." asking me to join to get a login.

<img width="1407" alt="Screenshot 2020-11-03 at 16 38 23" src="https://user-images.githubusercontent.com/14498/98006897-0ef30c80-1df3-11eb-98f7-276f6216fb91.png">

This raises few questions:

1) Why should I have to be a member to post about an event?  This could trigger to the creation of non active members. Ex. Some communication people that were just advertising about an erlang that welcome our ecosystem
2) The page doesn't say until I click to the link it's a feature reserved to members.
2) I don't understand at all what is supposed to mean "If you know about a related event that is not yet listed here or that you run on your own, contact us at events@erlef.org" How it's different from posting an event? What does mean related in such context? 

Imho this pages should be reworked to be more friendly for external communication. I would make the form open to anyone so it would be easier to post a simple meetup.

**Comment by starbelly** [comment]
I think that's fair.

**Comment by starbelly** [comment]
@benoitc I thought about this some more, while I think you shouldn't have to have a membership to post an event, I'm not sure we should allow anonymous posting. Perhaps we can support logging in from github, etc.

**Comment by benoitc** [comment]
well since it's about posting an event it must not be anonymous indeed. We could ask for the name, email and a phone number.  Also I guess a post don't trigger a an update of the website directly right? So in such case we can introduce some review also, even call the author if needed. Thoughts?

**Comment by starbelly** [comment]
Yeah that's true, they have to  be reviewed. I suppose in that regard it would be fine.

**Comment by paulo-ferraz-oliveira** [comment]
I don't get the issue @benoitc mentions, but agree with the rest of the discussion regarding non-anonymous posting: there should be some reference to the origin and/or an approval process.

**Comment by starbelly** [comment]
This has been discussed a few times over now. We will accept events from anonymous sources via email now, but priority is given to members who submit events on the site. Closing this as resolved per the email capability.
