### ISSUE TITLE
Include footer in all pages

### ISSUE THREAD

**Issue by gamebox** [erlef/website#24]
Currently, the footer only shows on the home page.  To bring to parity with prod, let's include in the app layout so all pages have it

**Comment by starbelly** [comment]
That make sense  to me, our footer as far as the twitter feed and event list in the footer I'm not sure about though. I suppose this is a decision best left to a designe perhaps, but 100% agree the footer should be on every page. @desmondmonster thought?

**Comment by desmondmonster** [comment]
@gamebox  yeah, let's put the footer everywhere.  if we want to change the footer content, that's fine...perhaps the latest tweets only need to be shown on the homepage, in which case they can be extracted from the footer.

**Comment by starbelly** [comment]
For the moment, I just included the footer in all the pages via the layout. Can figure out the design details later. 

Closed via #32
