### ISSUE TITLE
Add interfaces on site to submit academic papers

### ISSUE THREAD

**Issue by starbelly** [erlef/website#240]
Not unlike events, academic papers were moved to the database. If they are to remain there we need to provide interfaces and update the instruction on the page for doing so. 

 Also not unlike events, these would not get automatically displayed on the site, rather they would need to be approved by an administrator.

**Comment by PrakharUniyal** [comment]
Hi! I'm trying to work on this issue.
I am unclear on logging in as a regular user/admin in dev mode for testing. I've created a .env-local file and copied everything from .env-example into it. Do I need to make any other changes to it?

**Comment by starbelly** [comment]
@PrakharUniyal I in fact just pushed up a bunch of changes last night related to this. You no longer need any environment variables set and so forth. You should now be able to simply start up the app and will see a dropdown in the headers in dev mode which will allow you to login as different personas.

**Comment by starbelly** [comment]
For clarity I have added a screenshot of what the menu should look like now in dev mode : 

<img width="936" alt="Screen Shot 2020-12-08 at 11 02 39 AM" src="https://user-images.githubusercontent.com/39971740/101516273-e5268b80-3944-11eb-9b18-72c68039016c.png">
