### ISSUE TITLE
Add "A Gradual Type System for Elixir" - new academic paper

### ISSUE THREAD

**Issue by adolfont** [erlef/website#242]
- A Gradual Type System for Elixir
- 24th Brazilian Symposium on Programming Languages -  SBLP 2020
- Mauricio Cassola, Agustín Talagorria, Alberto Pardo, Marcos Viera | English | Paid
- https://doi.org/10.1145/3427081.3427084

**Comment by adolfont** [comment]
There is a video at  https://zenodo.org/record/4086203#.X76g6-mSm1s

**Comment by starbelly** [comment]
Can add this in a bit. We don't currently have a field for videos. Are you suggesting that or just you just added the video here for reference?

**Comment by adolfont** [comment]
If you dont't have a field for videos, just the link to the paper is enough.

**Comment by starbelly** [comment]
@adolfont I think we should, we can make that happen as part of #240. We'll get just the paper added for now.

**Comment by starbelly** [comment]
Added on site. Closing this as resolved.
