### ISSUE TITLE
Stipend Proposal Form -- Development Work

### ISSUE THREAD

**Issue by natalia-chechina** [erlef/website#250]
We discussed the current Stipend proposal form in the Embedded WG and to us, it seems the form does not fit proposals for the development work. So, we propose a revision. Specifically, we propose moving **Stipend Type** box to the top of the application form, and then applicants to be presented with the structures as in the attached excel file.
[EEF-proposal.xlsx](https://github.com/erlef/website/files/5848920/EEF-proposal.xlsx)

**Comment by starbelly** [comment]
@natalia-chechina Thank you! I think this greatly simplifies the stipend form, which I have always felt is a bit overwhelming. I'm fully on board with adjusting the form to conform to this spec 💯

**Comment by starbelly** [comment]
@natalia-chechina I have a question about the intention of the layout in the spread sheet. Is the intention for the form to look this way when development work is selected? The original form would be displayed for other types, is that correct?

**Comment by natalia-chechina** [comment]
@starbelly that's a good question! The thing is that we only looked at the form from the Development Work perspective... it seems the current version of the form suits quite well for Conference applications, but we did not check it against other categories... Could you share the link to the current (aka Conference) application form? You are right since we change that part of the web-site we should revise all types of submissions.

**Comment by starbelly** [comment]
@natalia-chechina Well, the form for all stipends is currently just https://erlef.org/stipends/ , that's part of the problem I believe. I think there's two approaches we can take here : 

 1. Changing the type of stipend changes the form
 2. Alternatively, we could have individual tabs on the side for each different type of stipend. 

But yeah, the way the form is currently (on the site) it mostly seems suited for events (conferences) and this is confusing if you're applying for something else. 

Ideally, we have one form that is suitable for anything to keep the amount of code down to a minimum, but if we have to, I think one of the two options above shall work. Thoughts?

**Comment by natalia-chechina** [comment]
Thank you @starbelly ! The thing is that I cannot access the form... when I click https://erlef.org/stipends/ it just gives me the page with general information... and when I click on on the form link it gives me https://erlef.org/stipends/# and just reloads the page...
I like the idea of putting the stipend type option at the top and then loading the form depending on what is chosen in that field :).

**Comment by starbelly** [comment]
@natalia-chechina sounds like javascript problems :( Maybe you have something blocking the js on the page from being executed. 

All I can do is attach a screen shot of the form : 

![Screenshot_2021-01-29 Erlang Ecosystem Foundation - Supporting the BEAM community](https://user-images.githubusercontent.com/39971740/106307080-81be2900-6224-11eb-8bb9-80a70ce8efbb.png)

**Comment by starbelly** [comment]
@natalia-chechina I'll take a look at adjusting the form on a per type basis soonish.

**Comment by starbelly** [comment]
This has been resolved via 75d2170 ❤️
