### ISSUE TITLE
Add blogs section to the community page

### ISSUE THREAD

**Issue by starbelly** [erlef/website#287]
A blogs section should be added to the community page, it may be there should be sub-sections, but it's not clear yet : 

We can use sources gathered in the marketing wiki as a start : https://github.com/erlef/marketing-wg/wiki/Community-Sources

**Comment by juhalehtonen** [comment]
FYI, I started looking into this one just to get my feet wet with how the website is built :)

**Comment by juhalehtonen** [comment]
My MR is pending for copy. Shall I simply suggest something in there, or do you want to have a say about them up front? :)

**Comment by starbelly** [comment]
@juhalehtonen I would go ahead and write something about them, then we can review.

**Comment by juhalehtonen** [comment]
Whoops, forgot to add a description that would have auto-closed this one :)

**Comment by juhalehtonen** [comment]
Just poking you @starbelly as a friendly reminder that this issue can be closed :-)

**Comment by starbelly** [comment]
Thanks :)
