### ISSUE TITLE
Affiliates page

### ISSUE THREAD

**Issue by starbelly** [erlef/website#289]
There are some associations that link to us and we should link back to them, this would be the start of an affiliates program. 

We need a simple page listing our affiliates with links back to their sites, below is a list of affiliates we can start with :  

 - elixir-lang.org
 - erlang.org
 - https://www.ow2.org/view/Membership_Joining/Associate_Organizations
 
 The page should also have a link to a contact, mostly like the marketing or the board which people can click on to let us know they are or would like to be an affiliate.

**Comment by joaquinalcerro** [comment]
Should we add a page similar to the Community one for Affiliates?

**Comment by starbelly** [comment]
@joaquinalcerro  I think the affiliates page should be its own page that we can link to in the navbar or footer (or both).

**Comment by joaquinalcerro** [comment]
I think we can close this issue @starbelly . 👍

**Comment by starbelly** [comment]
Indeed. Closed via #347
