### ISSUE TITLE
Moving 'Events" to a top level tab

### ISSUE THREAD

**Issue by ahw59** [erlef/website#300]
Is it possible to create a top level tab to the 'Events' page in the 'Join Us! Sponsors ... Log in' ribbon

**Comment by starbelly** [comment]
@ahw59 We can and it was that way, but the top menu started to get very cluttered. That said, I don't have strong feelings.

**Comment by paulo-ferraz-oliveira** [comment]
FWIW, it's already in Resources > Events. And the main page has a (quite visible) "View All Events →" element.
