### ISSUE TITLE
Missing news route for working-groups

### ISSUE THREAD

**Issue by starbelly** [erlef/website#35]
Currently on the live site we have posts as "wg" or working-groups. I think perhaps that these posts should be under "eef" (i.e., /news/eef). While I have added the actual post in the repo, it is currently not displayed anywhere.

**Comment by joaquinalcerro** [comment]
@starbelly 

What you have right now is that you call the news by id (ej. /news/time-is-running-out) and works but what you are trying to achieve is:
1. Show the news for each working group separately
2. The id will represent the working group name
3. Create a folder under the post directory for each working group name
4. New posts should go under its respective working group

So, to call a post we should call:
    /news/<wg name>/posts/<id>

Please let me know if I am correct? or your thoughts to see if I can help.

Best regards,

**Comment by starbelly** [comment]
Correct. The way it is currently setup is to "query" multiple blogs to find the post. The way you suggest is indeed how it was originally and I don't have an issue going back to that.

 I think the rationale for the current method was shorter url's and less setup. Let's see what @desmondmonster thinks.

**Comment by joaquinalcerro** [comment]
Well, it's not me trying to go back. I was just trying to understand the issue to work on it. Lets wait for @desmondmonster comments.

As I understand, we have been avoiding to use a database but checking the other issue, the voting system, I went to the https://www.heliosvoting.org website and the requirements include a PostgreSQL Database so I am thinking that if we are finally going to add a database to the website, we might consider using it to store the posts as well. What is the approximate time frame to add the voting system feature?

Let me know your thoughts.

**Comment by starbelly** [comment]
I see. I misunderstood. I'm not strongly tied to either way that being said. 

 As for helios voting, that option is still not set in stone and before I could comment on a time frame that option definitely needs to be set in stone 😁

**Comment by starbelly** [comment]
See https://github.com/erlef/website/pull/38

**Comment by starbelly** [comment]
@joaquinalcerro My plate if a bit full. I opened up #38 merely as a brain storm, would you like to grok what was done and start a new PR?

**Comment by joaquinalcerro** [comment]
Sure, I will give it a try and creating a new PR. Cool.

**Comment by starbelly** [comment]
Awesome! ❤️ Once you get a PR open I will close my draft.

**Comment by starbelly** [comment]
Closed via #39
