### ISSUE TITLE
Reconcile differences between content in app and live site

### ISSUE THREAD

**Issue by starbelly** [erlef/website#4]
There are some minor differences in content between what's currently in the app and what's live on the site right now. This need to be enumerated and worked into the app.

**Comment by gamebox** [comment]
I'll look into mapping this out this week.

**Comment by gamebox** [comment]
I've got a doc in progress outlining these differences.  I'll upload as a gist and link here when ready so we can work together to create the necessary issues.

**Comment by starbelly** [comment]
Most of these issues I believe have. been squashed. I'll close this. Remaining issues should be opened up as one-offs.
