### ISSUE TITLE
Cannot submit stipend through the website

### ISSUE THREAD

**Issue by pablocostass** [erlef/website#403]
Hello there!

I tried submitting a conference stipend proposal using the form available at https://erlef.org/stipends/form?type=conference, yet every time I tried I got a "413 Request Entity Too Large" response.

I would expect this to happen when the file attachment exceed the limit of 8MB, yet the only attachment my proposal had was of 3.7MB.

I have been told about other ways of sending the stipend proposal (via email, in short), but this might affect others too in the future.

**Comment by starbelly** [comment]
This is quite old, I left it open as a reminder initially. I think we resolved this, but we'll double check.

**Comment by starbelly** [comment]
RIght, when this ensued the default was raised to 8MB. Closing as resolved.
