### ISSUE TITLE
Simplify calendar event creation using google calendar

### ISSUE THREAD

**Issue by starbelly** [erlef/website#43]
Currently adding an event is mostly a manual job, lots of copy/pasta from existing sources which makes for an unpleasant operator experience and error prone. I think we can make use of fullcalendar's gcal support to simplify adding events as well as not having to create blog posts for said events. 

  The idea would be to add events to a specific google calendar which fullcalendar would pull in. Instead of relying on blog posts for the show route on /events this would have to be completely dynamic and the page would be build using nothing but supplied params and/or hitting google api to get all the information needed to build the page. 

 It may also be possible to subscribe said google calendar to other calendars to further limit how much work has to be done for events to end up on the site. 

The alternative would be to simplify creation of events posts from the command line. This would entail the mix task reaching out to sources such as google calendar to get as much info as possible to limit the amount of manual work done (optimally none) when adding events.

**Comment by joaquinalcerro** [comment]
@starbelly 

What comes to my mind is: who is going to be responsible to add a event to the calendar. The final user?

Love the idea of using what's on the market like Google Calendar and integrate it to the website. This is something that a lot of people use and are familiar with so from that users perspective, it will be simple to use.

If the events are going to be posted by a power user, command line might work.

From our perspective, parsing the information of the event might be challenging if the user doesn't use a standard form (assuming we are not only going to capture the title, date and time of the event). So I am thinking that the user will add the event and much more details of it in the "body" of the calendar meeting.

What do you think about integrating with Meetup or a similar type of event handling application? That might give the event organizer or groups more tools to followup and to make the most out of the event and from the website perspective, we just register and link it to the other site.

Let me know your comments.

**Comment by starbelly** [comment]
Someone designated for managing the would-be google calendar would be responsible for adding events to it.  With fullcalendar you don't need to parse anything. fullcalendar will your an api key to fetch events and display them in the calendar. We would instruct fullcalendar (via js callbacks) to make a link for /events/<slug>?gcal_event_id=some_gcal_event_id.... from there we could get utilize the calendar api at google to get all the information needed for displaying the event the way it currently is. So, there would be no scraping etc.

https://developers.google.com/calendar/v3/reference/calendars#resource 

We also want to integrate with meetup, but that can also be done via gcal. Specifically you can sync meetup.com events to a google calendar. The same people responsible for adding events to google calendar could also tag events that the calendar is subscribed to. That way we get everything in one go and don't default to displaying every single event our google calendar might be subscribed to. 

 Further integration with meetup.com is possible though, but outside the scope of this issue.

**Comment by joaquinalcerro** [comment]
Cool... lets get started... I will explore how fullcalendar works this weekend and try to get something to work on. Best regards.

**Comment by starbelly** [comment]
👍 There is a google calendar plugin for fullcalendar : https://fullcalendar.io/docs/google-calendar

 What I was doing was simply get an env from the system which had the google calendar api key, then passing that on to fullcalendar. By default it links to a new event template, and that's as far as I took it.

**Comment by benoitc** [comment]
I wouldn't worry much maybe a simple mail would be enough though. This is what doesthe Cloud Native Foundation : https://www.cncf.io/community/calendar/

Also what is the impact of the plugin for the GDPR?

**Comment by starbelly** [comment]
This issue is now obsolete. We have moved to displaying events in a vertical list vs using an actual calendar so closing this issue in light of that.
