### ISSUE TITLE
Display UTC timezones as local in event show template

### ISSUE THREAD

**Issue by starbelly** [erlef/website#44]
Currently we display the UTC time. It would be nice to display this in local time relevant to the area where an event is taking place. This could be done using moment and moment-timezone. 

https://momentjs.com/timezone/

**Comment by RudolfMan** [comment]
No need for momentjs. That could be done on the back end.

**Comment by RudolfMan** [comment]
I think it's better instead of time_offset for events use timezones.. so that no confusion would be for places that use daylight savings etc.

**Comment by starbelly** [comment]
Going to close this issue. If we need another issue around time zones, feel free to open one. Thanks.
