### ISSUE TITLE
Site down!

### ISSUE THREAD

**Issue by peerst** [erlef/website#456]
Firs thought its the Amazon outage but that was yesterday

**Comment by brainlid** [comment]
Down again today

![image](https://github.com/erlef/website/assets/808984/c310bfb0-aba2-4ef2-a08a-e74a9b766553)

**Comment by brainlid** [comment]
Okay, I realized it's not down. I can just can't view it when logged in. When I visit it in private browsing it works. I can't hit the `/logout` link as a GET because it requires a POST.

I fixed my personal issue by clearing the cookies/session/localstorage and re-logging in. :man_shrugging:

**Comment by brainlid** [comment]
No longer a problem. Close the issue.

**Comment by starbelly** [comment]
There were several issues. The main was twitter changed their policy. Specifically, they do not allow reads if you're on the "free tier" via the API anymore. 

The cookie issue has cropped every so often, but not often (we see all 500(s) that ensue). We can look and see if there's something we can do on our (it's not clear if it's a cache invalidation problem on our side or if it's a wildpricot problem).

**Comment by pdgonzalez872** [comment]
This can be closed maybe?

**Comment by starbelly** [comment]
@pdgonzalez872 I think we should leave it open now for visibility and thank you for opening this btw.

**Comment by starbelly** [comment]
I commented on the wrong issue, I meant to leave the other one open. Closing this one, and going to re-open the other issue (vultr object storage issues).
