### ISSUE TITLE
Reconcile style differences between app and live site.

### ISSUE THREAD

**Issue by starbelly** [erlef/website#5]
There are some minor style differences between the app and the live site. As an example, while both use the same font, they appear a little bit different. The differences need to be enumerated here, then broke up into issues. In some cases, we may prefer how something looks or is laid out in the app vs the site.

**Comment by gamebox** [comment]
I've got a doc in progress outlining these differences.  I'll upload as a gist and link here when ready so we can work together to create the necessary issues.

**Comment by starbelly** [comment]
The bulk of this is done, so am closing this issue. Any remaining issues should be opened up as on-offs.
