### ISSUE TITLE
document on the events page how to send an event

### ISSUE THREAD

**Issue by benoitc** [erlef/website#57]
it's hard to know from the events page how to send an event and where to send it. It would be good to add a aquick test describing how to do  it on this page, wouldn't it?

**Comment by starbelly** [comment]
Agreed and a form for submitting an event to boot. Specifically, you fill out a form to for an event, hit submit and a markdown file would be created and attached to an email which goes to marketing group.

**Comment by starbelly** [comment]
Closing this as obsolete, you will now be able to submit events on the site itself, will go out in the next few days.
