### ISSUE TITLE
[EVENT] new French Erlang/Elixir meetup in Paris

### ISSUE THREAD

**Issue by benoitc** [erlef/website#58]
can you add the new French Erlang/Elixir meetup in Paris to the calendar?

Date: 2019/10/08 between 7pm to 9pm
Location: Stuart (https://stuart.com) : 8 Avenue des Ternes, 75017 Paris
Event page: https://www.meetup.com/Erlang-Paris/events/265207130/

**Comment by benoitc** [comment]
@starbelly thanks! However you put it on 2019/10/18 instead of 2019/10/08 :) Can you fix it?

**Comment by starbelly** [comment]
@benoitc 🤦‍♂ oops.... fixed.
