### ISSUE TITLE
Voting system

### ISSUE THREAD

**Issue by starbelly** [erlef/website#6]
The site needs to integrate with the voting system that Benoit suggested. 

>  I still have to look at some different voting system but so far I think heliosvoting could fit our need: https://www.heliosvoting.org
> It provides the following features:
> * privacy: ballots are anonymous
> * verifiable: each votes is tracked (you can only vote once for ex)
> * opensource
> * verified
> We are using it in the PSF and it's works verifiable. It is also use by the OSI and many other orgs around the world. We can quickly discuss it but I also think it should be discussed at the board level. Thoughts?
> Benoît

**Comment by gamebox** [comment]
Seems like we would need to run a separate instance for this service.  But we could easily create a docker image to deploy it.  Should be relatively easy depending on IaaS/PaaS. 

One possible concern is that it seems that voting can only occur after logging in with a Facebook or Google account.  I think most people should have one or the other, but it _may_ leave some members without such an account unable to participate.

**Comment by starbelly** [comment]
This should not require another service. We should be able to integrate from the client side. However, that is an interesting point you raised. Not everyone is going to have facebook, google, etc. and/or willing to make an account. So, need to think about that some more 🤔

**Comment by gamebox** [comment]
Re: the service.  It wasn't obvious from the documentation how to use this as a third-party service.  If there is in fact an API to talk to a service with hosted elections, please point that out.

**Comment by starbelly** [comment]
I think it's more of a embed this form on your static site type of offering. I could be wrong, I have not looked at in detail yet.

**Comment by gamebox** [comment]
Sorry I've been a little quiet recently.  Would like to look into more this week.

**Comment by starbelly** [comment]
Closing this until a voting system has been decided on.

**Comment by gamebox** [comment]
I think the most important thing to do here is to think out loud about exactly the requirements are for any voting system that we would wish to adopt.

Here's a list of voting systems that are not open source: https://www.capterra.com/voting-software/?utf8=%E2%9C%93&feature%5B1%5D=27595&platform%5B1%5D=8&commit=Apply+Filters&sort_options=

I've went through open source options, and nothing really looks appealing to me.

**Comment by joaquinalcerro** [comment]
So we had a small email chat with @starbelly about this issue. Creating a voting system from the ground up will be a challenge and time consuming so, IMO if we want it fast, we should integrate one.

I found a Voting System that is in beta now and will be offered as a service. It is actually a serverless application hooked to the ethereum blockchanin. @starbelly as going to talk with other members of the foundation and give us their feedback about it.

@starbelly can you give us some feedback to try address this issue? Thanks @gamebox

**Comment by gamebox** [comment]
No problem.  I'm available to help on the integration if need be.

**Comment by joaquinalcerro** [comment]
Cool... 😎.

Let's wait for their feedback and take it from there.

Best regards

**Comment by RudolfMan** [comment]
What are the requirements of voting system?

**Comment by starbelly** [comment]
@RudolfMan The minimal requirements would be : 

  - it is OSS
  - it is something we don't have to maintain
  - allows for anonymous results but authenticated voting
  - is secure :)

**Comment by starbelly** [comment]
Closing this for now, we will be using wildapricot voting system for the foreseeable future. Integrating it with this app is another issue.
