### ISSUE TITLE
Add community page

### ISSUE THREAD

**Issue by starbelly** [erlef/website#61]
Similar to erlang.org or elixir-lang.org we should have a community page with useful links to resources and various parts of the communities.

**Comment by adolfont** [comment]
Excellent idea! How can I help, @starbelly ?

**Comment by starbelly** [comment]
@adolfont short of making a page to get things started, suggestions are definitely a way to help... what do you think should go on this page? I think grabbing what's on the erlang and elixir community pages and merging them is a good start. Thoughts?
