### ISSUE TITLE
Events process

### ISSUE THREAD

**Issue by pdgonzalez872** [erlef/website#79]
This is somewhat related to https://github.com/erlef/website/issues/57, but I think a little different so I decided to create a new issue for it.

I think we all agree that the more we involve the community the better the results would be for gathering events. Creating an MR for each event does not sound scalable, creating a form that mimics what ElixirForum already does also seems less than optional as well.

I talked to https://elixirforum.com/u/AstonJ (he is the main maintainer for the forum) and he suggested we could use a thread (would be pinned, let's name it `EEF Events` for now) where all we would need to do is paste links to other threads ([eg](https://elixirforum.com/t/2019-10-25-elixirconfla-medellin-colombia-first-in-latin-america/22365)) in the `EEF Events` thread.

Here is the events/meetups page: https://elixirforum.com/c/events-confs-meet-ups, we could also the results in `json` https://elixirforum.com/t/2019-10-25-elixirconfla-medellin-colombia-first-in-latin-america/22365.json

I suggest we look into a way of scraping the `EEF Events` thread on ElixirForum for events that we post and curate. We could add a couple of rules (filter on `posted_by` ) and I think we could leverage the data that is already is available to us on ElixirForum.

This would also give folks a way to discuss events and have a platform to engage with other users.

Thoughts?

**Comment by starbelly** [comment]
I think that's a sound idea. I'm going to wait to comment on this further as any decisions in this area will be affected by things that will fall out of the infrastructure group. Hang tight!

**Comment by starbelly** [comment]
I'm not sure this issue is still relevant, but I'm not sure it's not either 😁 You can now submit events on the site, but this issue wasn't exactly around this. @pdgonzalez872 do you think this is still relevant?

**Comment by pdgonzalez872** [comment]
Close it! :)
