### ISSUE TITLE
add a link to OW2

### ISSUE THREAD

**Issue by benoitc** [erlef/website#81]
We are associate to OW2, would be good to link to their site as they do:
https://www.ow2.org/view/Membership_Joining/Associate_Organizations

**Comment by pdgonzalez872** [comment]
where would we put that type of link?

**Comment by pdgonzalez872** [comment]
actually, the link you sent the first time has a good name: `Associate Organizations`. Maybe we add it there?

**Comment by benoitc** [comment]
hrmmm this link should have been added a long time ago. Can someone take care of it?

**Comment by starbelly** [comment]
This issue has been resolved via #115
