### ISSUE TITLE
Add academic papers page

### ISSUE THREAD

**Issue by pdgonzalez872** [erlef/website#87]
Hi!

I created a thread on Elixir Forum asking about a list of academic papers involving the Beam[0]. I thought of different ways to make this more visible to the community other than the Elixir Forum. I thought it would be a good idea to not reinvent the wheel and use something that already existed, so I found Papers We Love[1]. I created an issue asking about the convention of adding papers and and being able to filter/tag different papers[2]. It is currently open.

Related to this, I think it would be good to add an `Academic Papers` section, where we can curate the content we show and organize the content how we want to.

I suggest a simple page where we can link the papers and tag them however we would like. The example I used in the other repo still stands. This would be a link to a paper:

- `Making Reliable Distributed Systems in the Presence of Software Errors | Erlang`

I don't want to add short descriptions to the links, as this is yet more work to get the info out there. In my opinion, just links would suffice. We sort alphabetically and call it a day.

Thoughts?

cc: @miriampena 

[0] - https://elixirforum.com/t/list-of-academic-research-papers-involving-elixir-erlang/25686/11
[1] - https://github.com/papers-we-love/papers-we-love
[2] - https://github.com/papers-we-love/papers-we-love/issues/581

**Comment by lauramcastro** [comment]
I would sort chronologically, not alphabetically.

**Comment by pdgonzalez872** [comment]
@lauramcastro that's fair! +1

**Comment by starbelly** [comment]
Absolutely wonderful idea.

**Comment by pdgonzalez872** [comment]
Alright, I'll tackle this if that's alright.

**Comment by starbelly** [comment]
Definitely welcome and appreciated it.
