### ISSUE TITLE
Multiplayer Game Server for Turn-Based Mobile Games in Erlang (Feb 2013)

### ISSUE THREAD

**Issue by marcelfahle** [erlef/website#98]
Anders Andersson: 
Multiplayer Game Server for Turn-Based Mobile Games in Erlang (Feb 2013)

https://pdfs.semanticscholar.org/62c5/81a08fcb58cb89586486a949376d984a3303.pdf

**Comment by pdgonzalez872** [comment]
Hi @marcelfahle ! Thanks for mentioning this! This seems very interesting and along the lines of what we want showcased. ❤️

Would you please create a PR similar to this one? https://github.com/erlef/website/pull/100.

Thanks again!

**Comment by pdgonzalez872** [comment]
closed by https://github.com/erlef/website/pull/101
