### ISSUE TITLE
A Generic Game Server (2011)

### ISSUE THREAD

**Issue by marcelfahle** [erlef/website#99]
A Generic Game Server

Jonatan Pålsson
Richard Pannek
Niklas Landin
Mattias Petterson

https://jeena.net/t/GGS.pdf

**Comment by pdgonzalez872** [comment]
@marcelfahle, similar feedback to https://github.com/erlef/website/issues/98, This is great content, please open a PR? You can combine this one and https://github.com/erlef/website/issues/98 if you'd like.

Thank you! ❤️

**Comment by marcelfahle** [comment]
Sure thing @pdgonzalez872 ! 😄

**Comment by pdgonzalez872** [comment]
closed by https://github.com/erlef/website/pull/101
